### ISSUE TITLE
Models Builder for “simpler” sites? 🤔

### ISSUE THREAD

**Issue by enkelmedia** [Adolfi/UmbracoNineDemoSite#10]
Hi Denis (and other contributors)!

Great work on this one! Really awesome and thanks for sharing it! I would definitely contribute in the future! I really think that this project has the potential of being a great source of inspiration and best practice for Umbraco websites going forward. Like a documentation that actually shows how to solve the “real” problems implementors are facing.

I’m wondering about ditching Models Builder. Is there a really good reason not to use it in a best practice example? 

I do get that you don’t want to expose the whole cms-model (IPublishedContent) in the view but wouldn’t the mapping in the controllers be cleaner/safer if done from a models builder model? The models created by Models Builder is basically what you are doing manually in the controllers but without all the constants for property names, or actually more “automatic constants” with the strongly typed names. They also keep information about any Compositions so one can go ie:

```csharp 
if(model is IPageWithHero hero) {
…
}
```

It’s also safer for any changes in the document type - MB would give a compiler warning. The current solution will throw at runtime in best case or silently fail/behave strange if I forget to change the constant for the property alias.

Did you actively decide not to go with Models Builder? It would be nice to hear more about why and maybe document that decision.  

And also, I think it sounds bad to indicate that models builder is only suitable for “simpler projects” (in the readme) - that might put a lot of people in the wrong direction, I would say that it might be a matter of taste but from a technical standpoint running without Model Builder is a less safe and sustainable way of building a complex and maintainable solution with Umbraco - more manual work and more prone to errors.

Would be nice to hear your thoughts? 

Cheers man!

**Comment by Adolfi** [comment]
Hey Markus, thank you so much for being involved in this.
And thanks for your kind words regarding this project in terms of being a good source of inspiration and documentation.
I will try to break down all your questions and answer them separately.

**1. Regarding the ModelsBuilder being used in "simpler" sites/projects.**
I think you are paraphrasing me here, I'm actually never saying that ModelsBuilder is good for simples sites or projects. Im saying its a **simpler way** of building sites, which is a huge difference. That being said, I do agree that using the phrase "simpler" is in poor taste and should be avoided. Thank you for this feedback!

**2. Is there a really good reason not to use it in a best practice example?**
No, there isn't. I started this project on the very first beta and at that point there where some issues with ModelsBuilder generating .cs files that where not compiling. Therefor I went in a direction of not using ModelsBuilder. At that point I had no intention of doing a public demo site, it was just used for personal project. But now as it is being viewed as a "best practice" it makes a lot of sense adding ModelsBuilder models. And as you mentioned, what I'm doing in my own models at the moment is basically what models builder is doing anyway, except automagically. I would love to see an update / PR from you (or someone else) where models builder is introduced. As long as all the logic is still through controllers (i.e not just throwing ModelsBuilder models straight in a view without going through a controller). Possibly also with partial modelsbuilder classes where necassary used in controllers. And that it's still testable of course. Then I have nothing agains ModelsBuilder being used in this demo site.

I will make sure to update the readme based on your feedback.

Cheers mate! ❤️

**Comment by enkelmedia** [comment]
Hi man!

I see where you're coming from makes sense! Hard to use something that does not work =D  

Also, it might be that my interpretation of your intent was wrong but it's always good to be super-clear (reg. the readme).

Thanks for the positive leaning towards my suggestions I'd be happy to help but probably need some time before I can get my hands dirty. I'll update here when I start, meanwhile - if someone want to grab it before just drop a comment here and we could work together.

// m

**Comment by Adolfi** [comment]
Awesome, thanks man! ❤️
I totally get that this kind of update would require some work and you might not have that time at the moment.
I'll leave this issue open for anyone to pick up if they feel inspired to update it.

Cheers!

**Comment by mistyn8** [comment]
Interesting topic of discussion. We're still using DTGEGridEditor in v9 and started with viewcomponents.. so I've seemed to end up have modelsbuilder, as a view model for dtge, then a ViewModel simplifying the modelsbuilder model to pass into the viewcomponent, which then has a ViewModel to pass back to the viewcomponent for rendering it's view.. :-) Seem to be creating a lot of overhead there. (and none of this can be fully accomplished in the backoffice anymore)

I think this feeds into another topic, that of is the umbraco backoffice (template/partial/model generation) all seen as legacy and not to be used in anger.. as we should be deploying source controlled templates/partials and compiled models as part of a deploy process.
Having used umbraco since v4 the integrated backoffice approach, as a cms for a developer abstracted out so much of the learning curve of underlying web forms and then MVC whilst still giving so much control (not to mention being able to hand over to a client and still allow them to do things that would normally require a developer) was part of the joy of working with umbraco.
Once setup it was completely plausible to just use the backoffice to do cms things.

Recent forum posts also talk about js/css also shouldn't be edited via the backoffice again as source control should rule.
But again that's the beatury of the umbraco backoffice.. no need for ftp/ssh etc just a web browser and a login!

I am a little downhearted that this USP is being eroded (that USP was why we went for umbraco in the first place over other CMS's at the time that enforced needing a season developer to even simply extend a template), but understand why the direction. 

(for simple sites where we leave the client able to use the backoffice for the should be source controlled items in order to have the best of both worlds we have taken to leaving the production site backed by a local git repo on azure app_services, so when coming back to the site as a developer we can fetch down the backup giving a git repo with all backoffice instigated changes ready to be staged. and committed)

There was also ModelsBuilder.Embedded in v8 that seemed to go the other way. No more intellisence in VS so hampering the developer. So this is a two way street ;-)

However, on the flip side I wouldn't be without source control, MVC separation of concern and testable code (though I don't do enough of that)
.
I wonder if the backoffice might ever be extended to allow editing of controllers? maybe in app_code for JIT compilation.. if that is even still a thing in .netcore? to make the backoffice holistic again? and pie in the sky could the backoffice not have some of the features of deploy ported (umbcloud) so that saving templates commits to your repo ?? to keep the USP?

Please know that I'm loving seeing your demo site evolve, and am indebted to you for simplifying the viewcomponents learning curve. Just the topic here resonated with some of the thoughts I'd been having lately, around the diminishing of the backoffice. to just a content,media.member and user manager.

**Comment by enkelmedia** [comment]
This is an interesting point, we often find what we have to reference some packages in our ".Core" (we actually call them .Web)-projects to be able to pass these "package specific models" to the views for rendering.

It's not really related to Models Builder or not as the underlaying model from something like `Content.GetProperty("intro")` would be what ever the ValueConverter returns so the models builder models only wraps a call like this:

```csharp
public string Intro => _content.GetProperty<string>("into")
```

But the problem is the same, the .Core-project might need to reference some of the package dlls to be able to pass the models to the view model. I still think it worth it and that passing the whole Models Builder-model to the view should be avoided.

**Comment by Adolfi** [comment]
That’s awesome Dirk, thank you for this! ModelsBuilder will be great for a demo site, as long as it’s still Testable and logic is still going trough controllers (ie not just throwing ModelsBuilder models straight in to views).

also would prefer it if the generated models would be generated to its own separate project, for example *.Models, for nice separation. What do you think?

**Comment by enkelmedia** [comment]
I was just about to add that I also think that the models can go in the same project - a separate project only for models would just make the it worse with all the dependencies.

I also think that it would be good to show how to use a "Property Editor Package" that ships with custom types for the models, ie:

https://our.umbraco.com/packages/backoffice-extensions/contentment/

https://our.umbraco.com/packages/collaboration/seo-visualizer/

**Comment by idseefeld** [comment]
I have startet with *Models Builder* in fork https://github.com/idseefeld/UmbracoNineDemoSite (select branch: ***modelsbuilder***)

After checking out branch ***modelsbuilder*** and building, go into back office ***settings > uSync*** section and import ***Settings*** and ***Content***.

Then goto ***settings : Models Builder*** and generate models (which should be outdated).

### What I have done so far:

1. Added a new project for generated models and added the necessary configuration in /appSettings.Development.json
2. Updated HomeViewModel using the generated strong typed model.
3. Updated Tests for Home controller

What do you think about this approach?

@enkelmedia Maybe I am not up to date with compiler capabilities regarding circular dependencies, but I think you need the generated models in a dedicated project to use them e.g. in the core project.
Here is a nice article which explains my concern in detail: https://stackoverflow.com/questions/38042130/what-is-a-circular-dependency-and-how-can-i-solve-it/38042916

**Comment by Adolfi** [comment]
Also, would it be possible to name the project .Models instead of GeneratedModels and place all the classes in the root of the project, since this is the only thing this project will ever contain Models its unnecessary with a folder called Models IMHO

**Comment by enkelmedia** [comment]
Hi guys!

Nice work on this one! I have never had an issue with circular dependencies, I was referring to dependencies on ie. Contentment etc. since a strongly typed model from a 3rd party property editor might be needed in the view model (as someone talked about earlier) a dedicated project for the models adds yet another project that needs to depend on this external property editor. Not an issue, more a matter of taste.

I would like to challenge @Adolfi on the approach of injecting the IPublishedContent into the view model, this ties the view model it self to the IPublishedContent-interface and Umbraco - I would argue that a mapper would be the cleanest way. Also sometimes the view model might consist of more than just properties on the current IPublishedContent, some of them might be cached or assembled from somewhere else.

**Comment by idseefeld** [comment]
Ok, circular dependency is not an issue when we use an extra project just for the generated models (btw. I have renamed it 😉).
My concern was with generating the models in the web-project. Because than the core-project needs to reference the web-project.

I have to reconsider your suggestion for `public IActionResult HomePage(Home model)`. At the first glance it sounds interesting. Let's see how this will work for testing...

**Comment by idseefeld** [comment]
@enkelmedia Ok, than we are on the same track. Good idea to put the generated models into .core project as we have only this extra project. Your mostly used projects structure makes sense to me, but for now let's stick with one extra project in this Demo.

@Adolfi What do you think about the consolidation of .Models and .Core project? 
Will it make sense you create a *modelsbuilder* branch and I make PRs into that branch (make collaboration probably simpler)?

**Comment by Adolfi** [comment]
I guess most of the things we are discussing here in terms of project structure all boils down to taste and personal preferences. I don’t really have a super strong opinion on where the models should be placed. Both is fine by me, every one use different approach  and I don’t think we will regret the decision regardless of which one we choose.

Otherwise I’m afraid we may be stuck discussing these things until the end of time. 😊

@enkelmedia agreed, we can add our own mapping logic instead of installing a mapping project.

@idseefeld sounds good, however I won’t find time to start that branch before sometime next week unfortunately.

**Comment by Adolfi** [comment]
@enkelmedia agreed! Simple mapper-class is 100% enough!
